version: '3'

services:
  openresty:
    image: openresty/openresty:1.21.4.3-1-jammy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./openresty/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/local/openresty/nginx/html
      - ./openresty/letsencrypt:/etc/letsencrypt
    depends_on:
      - strfry

  strfry:
    image: relayable/strfry:latest
    volumes:
      - ./strfry/config/strfry.conf:/etc/strfry.conf
      - ./strfry/db:/app/strfry-db
      - ./strfry/plugins:/app/plugins
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./openresty/letsencrypt:/etc/letsencrypt
      - ./html:/usr/local/openresty/nginx/html
    command: certonly --webroot -w /usr/local/openresty/nginx/html --force-renewal --email daniel@nos.social -d relay.nos.social --agree-tos
