version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
    depends_on:
      - strfry

  strfry:
    image: relayable/strfry:latest
    volumes:
      - ./strfry/config/strfry.conf:/etc/strfry.conf
      - ./strfry/db:/app/strfry-db
      - ./strfry/plugins:/app/plugins
