version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/var/www/html
      - ./nginx/letsencrypt:/etc/letsencrypt
    depends_on:
      - strfry

  strfry:
    image: relayable/strfry:latest
    volumes:
      - ./strfry/config/strfry.conf:/etc/strfry.conf
      - ./strfry/db:/app/strfry-db
      - ./strfry/plugins:/app/plugins
